### ISSUE TITLE
Second travis test failing consistently. 

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#4778] opened 2017-09-11 16:38 UTC
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project druid-processing: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/travis/build/druid-io/druid/processing && /usr/lib/jvm/java-8-oracle/jre/bin/java -Xmx768m -Duser.language=en -Duser.country=US -Dfile.encoding=UTF-8 -Duser.timezone=UTC -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -jar /home/travis/build/druid-io/druid/processing/target/surefire/surefirebooter6872093151481612081.jar /home/travis/build/druid-io/druid/processing/target/surefire/surefire4148885626359220171tmp /home/travis/build/druid-io/druid/processing/target/surefire/surefire_08792527364693215048tmp
```

Is being thrown again and again during travis automated testing on the second travis test.

**Comment by gianm** [comment] 2017-09-11 17:38
It seems that BufferHashGrouperTest is often started but not completed, suggesting that's the one that crashes the VM.

Raised #4779 to maybe help, on the guess that the way we're allocating the large buffers is causing the crashes. I think mmapping past the end of a file isn't kosher.

**Comment by gianm** [comment] 2018-09-07 05:10
Closing this -- haven't seen it in a while, and the issue is a year old.

**Closed by gianm** 2018-09-07 05:10 UTC
Labels: Area - Testing, Flaky test
