### ISSUE TITLE
Smart rebalancing through node deprecation

### ISSUE THREAD

**Issue by jstrunk** [apache/incubator-druid#316] opened 2013-12-02 23:33 UTC
There have been a few time that we've come across the situation where we want to replace nodes instead of updating in place. We are also considering moving to a side by side upgrade deployment system.

The status quo makes it difficult to replace the entire cluster efficiently. We have to spin up nodes, wait for rebalancing, kill an old node, wait for rebalancing, repeat.

It would be nice to be able to mark a node as retiring or soon to be deprecated so that its data would get replicated on the new nodes sooner. So, you could mark a node this way, and it would still be used for the segments it has, but it they would not be considered in the replica count.

**Comment by egor-ryashin** [comment] 2019-02-23 00:01
Looks similar to https://github.com/apache/incubator-druid/issues/3247

**Comment by leventov** [comment] 2019-03-29 20:08
Closing as duplicate of #3247

**Closed by leventov** 2019-03-29 20:08 UTC
Labels: Area - Segment Balancing/Coordination, Difficulty - Hard, Feature, Priority - High
