### ISSUE TITLE
Transient test error - timeout - testQueryWithSegmentSpec - io.druid.segment.realtime.RealtimeManagerTest

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#2976] opened 2016-05-17 17:28 UTC
https://github.com/druid-io/druid/pull/2971#issuecomment-219791505

**Comment by gianm** [comment] 2018-09-07 05:06
Closing this -- haven't seen it recently and the issue is a couple years old.

**Closed by gianm** 2018-09-07 05:06 UTC
Labels: Area - Testing, Flaky test
