### ISSUE TITLE
Transient test failure - KafkaIndexTaskTest. testRunOnNothing - ZkTimeoutException

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#3038] opened 2016-05-31 14:50 UTC
As per https://travis-ci.org/druid-io/druid/jobs/133474341

```
testRunOnNothing[buildV9Directly = true](io.druid.indexing.kafka.KafkaIndexTaskTest)  Time elapsed: 50.725 sec  <<< ERROR!
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 30000
    at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1223)
    at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:155)
    at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:129)
    at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:89)
    at kafka.utils.ZkUtils$.apply(ZkUtils.scala:71)
    at kafka.server.KafkaServer.initZk(KafkaServer.scala:278)
    at kafka.server.KafkaServer.startup(KafkaServer.scala:168)
    at io.druid.indexing.kafka.test.TestBroker.start(TestBroker.java:73)
    at io.druid.indexing.kafka.KafkaIndexTaskTest.setUp(KafkaIndexTaskTest.java:248)

```

**Comment by gianm** [comment] 2017-02-13 22:45
Even though a 30s timeout is pretty generous, my best guess is this was likely due to CI infrastructure being slow. I don't see anything that jumps out as wrong in the code. I'll leave this open in case someone sees it again but will untag the 0.10.0 milestone.

**Comment by gianm** [comment] 2018-09-07 05:05
Closing this -- haven't seen it recently and the issue is a couple years old.

**Closed by gianm** 2018-09-07 05:05 UTC
Labels: Area - Testing, Area - Zookeeper/Curator, Flaky test
