### ISSUE TITLE
LookupCoordinatorManagerTest transient faliure

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#2942] opened 2016-05-10 03:17 UTC
```
Tests run: 31, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.559 sec <<< FAILURE! - in io.druid.server.lookup.cache.LookupCoordinatorManagerTest
testGetLookupURL(io.druid.server.lookup.cache.LookupCoordinatorManagerTest)  Time elapsed: 0.53 sec  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at io.druid.server.lookup.cache.LookupCoordinatorManagerTest.tearDown(LookupCoordinatorManagerTest.java:125)
```

**Comment by gianm** [comment] 2018-09-07 05:06
Closing this -- haven't seen it recently and the issue is a couple years old.

**Closed by gianm** 2018-09-07 05:06 UTC
Labels: Area - Testing, Flaky test
