### ISSUE TITLE
not able to insert records

### ISSUE THREAD

**Issue by vadirajks** [apache/incubator-druid#7840] opened 2019-06-06 11:23 UTC
Hi,
for testing I am running it in single machine by referring to Apache Druid (incubating) Quickstart
(http://druid.io/docs/latest/tutorials/index.html)

Need help to fix below mentioned error:

Ver 
:apache-druid-0.14.2-incubating/

Json FIle:
{
  "type": "index",
  "spec": {
    "dataSchema": {
      "dataSource": "pageviews",
      "parser": {
        "type": "string",
        "parseSpec": {
          "format": "json",
          "timestampSpec": {
            "column": "timestamp",
            "format": "auto"
          },
          "dimensionsSpec": {
            "dimensions": [],
            "dimensionExclusions": [
              "eventId",
              "userId",
              "url"
            ],
            "spatialDimensions": []
          }
        }
      },
      "metricsSpec": [
        {
          "type": "count",
          "name": "count"
        }
      ],
      "granularitySpec": {
        "type": "uniform",
        "segmentGranularity": "DAY",
        "queryGranularity": "HOUR",
        "intervals": [
          "2015-03-01/2015-04-01"
        ]
      }
    },
    "ioConfig": {
      "type": "index",
      "firehose": {
        "type": "local",
        "baseDir": "/root/example4/druid-pageviews/",
        "filter": "events.json"
      }
    },
    "tuningConfig": {
      "type": "index",
      "targetPartitionSize": -1,
      "rowFlushBoundary": 0,
      "numShards": 1
    }
  }
}

Data :
{"eventId":"e1", "timestamp":"2015-03-24T14:00:00Z", "userId":"u1", "url":"http://site.com/1"}
{"eventId":"e2", "timestamp":"2015-03-24T14:00:01Z", "userId":"u2", "url":"http://site.com/1"}
{"eventId":"e3", "timestamp":"2015-03-24T14:00:02Z", "userId":"u3", "url":"http://site.com/1"}
{"eventId":"e4", "timestamp":"2015-03-24T14:00:03Z", "userId":"u1", "url":"http://site.com/2"}
{"eventId":"e5", "timestamp":"2015-03-24T14:00:04Z", "userId":"u2", "url":"http://site.com/2"}
{"eventId":"e6", "timestamp":"2015-03-24T14:00:05Z", "userId":"u1", "url":"http://site.com/3"}
{"eventId":"e7", "timestamp":"2015-03-24T15:00:00Z", "userId":"u1", "url":"http://site.com/1"}
{"eventId":"e8", "timestamp":"2015-03-24T15:00:01Z", "userId":"u4", "url":"http://site.com/1"}
{"eventId":"e9", "timestamp":"2015-03-24T15:00:02Z", "userId":"u3", "url":"http://site.com/2"}
{"eventId":"e10", "timestamp":"2015-03-24T15:00:03Z", "userId":"u4", "url":"http://site.com/2"}
{"eventId":"e11", "timestamp":"2015-03-24T16:00:00Z", "userId":"u2", "url":"http://site.com/1"}
{"eventId":"e12", "timestamp":"2015-03-24T16:00:01Z", "userId":"u4", "url":"http://site.com/1"}

ERROR:
2019-06-06T09:17:00,202 INFO [task-runner-0-priority-0] org.apache.druid.segment.realtime.appenderator.AppenderatorImpl - Shutting down...
2019-06-06T09:17:00,204 ERROR [task-runner-0-priority-0] org.apache.druid.indexing.common.task.IndexTask - Encountered exception in BUILD_SEGMENTS.
java.lang.IllegalArgumentException: Invalid max row count: 0
at org.apache.druid.segment.incremental.IncrementalIndex$Builder.buildOnheap(IncrementalIndex.java:433) ~[druid-processing-0.14.2-incubating.jar:0.14.2-incubating]
at org.apache.druid.segment.realtime.plumber.Sink.makeNewCurrIndex(Sink.java:336) ~[druid-server-0.14.2-incubating.jar:0.14.2-incubating]
at org.apache.druid.segment.realtime.plumber.Sink.(Sink.java:95) ~[druid-server-0.14.2-incubating.jar:0.14.2-incubating]
at org.apache.druid.segment.realtime.appenderator.AppenderatorImpl.getOrCreateSink(AppenderatorImpl.java:394) ~[druid-server-0.14.2-incubating.jar:0.14.2-incubating]
at org.apache.druid.segment.realtime.appenderator.AppenderatorImpl.add(AppenderatorImpl.java:244) ~[druid-server-0.14.2-incubating.jar:0.14.2-incubating]
at org.apache.druid.segment.realtime.appenderator.BaseAppenderatorDriver.append(BaseAppenderatorDriver.java:403) ~[druid-server-0.14.2-incubating.jar:0.14.2-incubating]
at org.apache.druid.segment.realtime.appenderator.BatchAppenderatorDriver.add(BatchAppenderatorDriver.java:106) ~[druid-server-0.14.2-incubating.jar:0.14.2-incubating]
at org.apache.druid.indexing.common.task.IndexTask.generateAndPublishSegments(IndexTask.java:1038) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
at org.apache.druid.indexing.common.task.IndexTask.run(IndexTask.java:473) [druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:419) [druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:391) [druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
2019-06-06T09:17:00,221 INFO [task-runner-0-priority-0] org.apache.druid.segment.realtime.firehose.ServiceAnnouncingChatHandlerProvider - Unregistering chat handler[index_pageviews_2019-06-06T09:16:55.389Z]

Thanks,

**Comment by vogievetsky** [comment] 2019-06-09 05:21
May I ask how you wrote that ingestion spec that you posted?
I can reproduce your issue and it seems to be because you are setting whacky stuff in the `tuningConfig`

`targetPartitionSize` and `rowFlushBoundary` are related to hadoop ingestion if I am not mistaken, in any case they are not even listed in the [native index docs](http://druid.io/docs/latest/ingestion/native_tasks.html)

I modified your spec to the one below by simply removing everything from the `tuningConfig` and it seems to work:

![image](https://user-images.githubusercontent.com/177816/59155322-a821c600-8a3b-11e9-9feb-dc42a5cc16d6.png)

Here is your spec with out the stuff in the  `tuningConfig`:

```
{
  "type": "index",
  "spec": {
    "dataSchema": {
      "dataSource": "pageviews",
      "parser": {
        "type": "string",
        "parseSpec": {
          "format": "json",
          "timestampSpec": {
            "column": "timestamp",
            "format": "auto"
          },
          "dimensionsSpec": {
            "dimensions": [],
            "dimensionExclusions": [
              "eventId",
              "userId",
              "url"
            ],
            "spatialDimensions": []
          }
        }
      },
      "metricsSpec": [
        {
          "type": "count",
          "name": "count"
        }
      ],
      "granularitySpec": {
        "type": "uniform",
        "segmentGranularity": "DAY",
        "queryGranularity": "HOUR",
        "intervals": [
          "2015-03-01/2015-04-01"
        ]
      }
    },
    "ioConfig": {
      "type": "index",
      "firehose": {
        "type": "local",
        "baseDir": "/Users/vadim/Downloads/",
        "filter": "events.json"
      }
    },
    "tuningConfig": {
      "type": "index"
    }
  }
}
```

**Comment by vogievetsky** [comment] 2019-06-09 05:55
Boom: a video reply https://www.youtube.com/watch?v=X3nQd0KuqPU just for you @vadirajks 

Here is the generated spec from the video:

```
{
  "type": "index",
  "dataSchema": {
    "dataSource": "pageviews",
    "granularitySpec": {
      "type": "uniform",
      "segmentGranularity": "DAY",
      "queryGranularity": "HOUR",
      "rollup": true
    },
    "parser": {
      "type": "string",
      "parseSpec": {
        "format": "json",
        "timestampSpec": {
          "column": "timestamp",
          "format": "iso"
        },
        "dimensionsSpec": {
          "dimensions": [
            "eventId",
            "url",
            "userId"
          ]
        }
      }
    },
    "metricsSpec": [
      {
        "name": "count",
        "type": "count"
      }
    ]
  },
  "ioConfig": {
    "type": "index",
    "firehose": {
      "type": "local",
      "baseDir": "/Users/vadim/Downloads/",
      "filter": "events.json"
    }
  },
  "tuningConfig": {
    "type": "index"
  }
}
```

**Comment by vogievetsky** [comment] 2019-09-26 04:36
Marking as solved. See my video reply ☝️

**Closed by vogievetsky** 2019-09-26 04:36 UTC
