### ISSUE TITLE
`io.druid.indexing.kafka.KafkaIndexTaskTest` timeout

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#3460] opened 2016-09-14 16:11 UTC
https://travis-ci.org/druid-io/druid/jobs/159894102 saw the following problem in TravisCI

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.druid.indexing.kafka.KafkaIOConfigTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.305 sec - in io.druid.indexing.kafka.KafkaIOConfigTest
Running io.druid.indexing.kafka.KafkaIndexTaskClientTest
Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.316 sec - in io.druid.indexing.kafka.KafkaIndexTaskClientTest
Running io.druid.indexing.kafka.KafkaIndexTaskTest
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

Assuming this isn't an actual lock-up, a potential solution here would be to break up `io.druid.indexing.kafka.KafkaIndexTaskTest` into more smaller test files, or to move some of the tests to integration tests (again, if appropriate)

**Comment by gianm** [comment] 2018-09-07 05:05
Closing this -- haven't seen it recently and the issue is a couple years old.

**Closed by gianm** 2018-09-07 05:05 UTC
Labels: Area - Testing, Flaky test
