### ISSUE TITLE
Transient failure ZkCoordinatorTest.testLoadCache

### ISSUE THREAD

**Issue by fjy** [apache/incubator-druid#2513] opened 2016-02-20 23:18 UTC
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 22.623 sec <<< FAILURE! - in io.druid.server.coordination.ZkCoordinatorTest
testLoadCache(io.druid.server.coordination.ZkCoordinatorTest)  Time elapsed: 18.676 sec  <<< ERROR!
java.lang.RuntimeException: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /druid
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
    at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
    at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1073)
    at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:274)
    at org.apache.curator.utils.EnsurePath$InitialHelper$1.call(EnsurePath.java:156)
    at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
    at org.apache.curator.utils.EnsurePath$InitialHelper.ensure(EnsurePath.java:148)
    at org.apache.curator.utils.EnsurePath.ensure(EnsurePath.java:102)
    at io.druid.server.coordination.ZkCoordinator.start(ZkCoordinator.java:129)
    at io.druid.server.coordination.ZkCoordinatorTest.testLoadCache(ZkCoordinatorTest.java:395)

**Comment by gianm** [comment] 2018-09-07 05:07
Closing this -- haven't seen it recently and the issue is a couple years old.

**Closed by gianm** 2018-09-07 05:07 UTC
Labels: Area - Testing, Area - Zookeeper/Curator, Flaky test
