### ISSUE TITLE
0.13.0-incubating tag does not compile

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#6831] opened 2019-01-10 03:42 UTC
```sh
$ git checkout druid-0.13.0-incubating
$ mvn clean test-compile -pl extensions-core/avro-extensions
[ERROR] /Users/charles.allen/src/druid/extensions-core/avro-extensions/src/test/java/org/apache/druid/data/input/AvroStreamInputRowParserTest.java:[127,81] cannot find symbol
  symbol:   method asMap(java.util.HashSet<java.lang.CharSequence>,<anonymous com.google.common.base.Function<java.lang.CharSequence,java.lang.Integer>>)
  location: class com.google.common.collect.Maps
[ERROR] /Users/charles.allen/src/druid/extensions-core/avro-extensions/src/test/java/org/apache/druid/data/input/AvroStreamInputRowParserTest.java:[138,89] cannot find symbol
  symbol:   method asMap(java.util.HashSet<java.lang.CharSequence>,<anonymous com.google.common.base.Function<java.lang.CharSequence,java.lang.CharSequence>>)
  location: class com.google.common.collect.Maps

```

For some reason the pig h2 dependency is rolling in guava but not shading it.

**Comment by drcrallen** [comment] 2019-01-10 03:56
oh, it is just a dependency thing. addinng

```xml

        <exclusion>
          <groupId>com.google.guava</groupId>
          <artifactId>guava</artifactId>
        </exclusion>
```

to the pig dependency fixes it

**Comment by jihoonson** [comment] 2019-01-16 23:31
It looks not a bug of Druid. @drcrallen would you please check and close this issue if it's not?

**Comment by jihoonson** [comment] 2019-05-07 19:08
I'm closing this issue. @drcrallen let me know if you think this is still valid.

**Closed by jihoonson** 2019-05-07 19:08 UTC
Labels: Bug
