### ISSUE TITLE
Transient failure on io.druid.server.namespace.cache.JDBCExtractionNamespaceTest testFindNew

### ISSUE THREAD

**Issue by fjy** [apache/incubator-druid#2160] opened 2015-12-24 05:01 UTC
Build: https://travis-ci.org/druid-io/druid/jobs/98409883

```
io.druid.server.namespace.cache.JDBCExtractionNamespaceTest
testFindNew[tsColumn](io.druid.server.namespace.cache.JDBCExtractionNamespaceTest)  Time elapsed: 4.362 sec  <<< FAILURE!
org.junit.ComparisonFailure: update check expected:<ba[z]> but was:<ba[r]>
    at org.junit.Assert.assertEquals(Assert.java:115)
    at io.druid.server.namespace.cache.JDBCExtractionNamespaceTest.assertUpdated(JDBCExtractionNamespaceTest.java:347)
    at io.druid.server.namespace.cache.JDBCExtractionNamespaceTest.testFindNew(JDBCExtractionNamespaceTest.java:288)
```

**Comment by fjy** [comment] 2015-12-31 05:26
This test is still failing due to timeouts

io.druid.server.namespace.cache.JDBCExtractionNamespaceTest
testFindNew[tsColumn](io.druid.server.namespace.cache.JDBCExtractionNamespaceTest)  Time elapsed: 64.075 sec  <<< ERROR!
java.lang.Exception: test timed out after 60000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at io.druid.server.namespace.cache.JDBCExtractionNamespaceTest.assertUpdated(JDBCExtractionNamespaceTest.java:488)
	at io.druid.server.namespace.cache.JDBCExtractionNamespaceTest.testFindNew(JDBCExtractionNamespaceTest.java:426)
Running io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.549 sec - in io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest
Running io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest
Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.508 sec - in io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest

**Comment by fjy** [comment] 2015-12-31 05:28
@drcrallen This test doesn't even run locally in IntelliJ, making it a gigantic pain to debug

**Comment by fjy** [comment] 2016-01-02 21:09
I give up trying to fix this test

**Comment by fjy** [comment] 2016-01-02 21:13
This is the current failure:
io.druid.server.namespace.cache.JDBCExtractionNamespaceTest
testFindNew[tsColumn](io.druid.server.namespace.cache.JDBCExtractionNamespaceTest)  Time elapsed: 63.353 sec  <<< ERROR!
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at io.druid.server.namespace.cache.JDBCExtractionNamespaceTest.tearDown(JDBCExtractionNamespaceTest.java:310)

**Comment by fjy** [comment] 2016-01-02 21:13
@drcrallen Please have a look. This is high priority.

**Comment by drcrallen** [comment] 2016-01-04 17:17
@fjy will check out

**Comment by fjy** [comment] 2016-01-07 05:09
@drcrallen reopening this issue as it appears to be still happening

**Comment by drcrallen** [comment] 2016-02-25 20:18
@fjy I need links to the failed test runs

**Comment by gianm** [comment] 2018-09-07 05:09
Closing this -- haven't seen it recently and the issue is a couple years old.

**Closed by gianm** 2018-09-07 05:09 UTC
Labels: Area - Testing, Flaky test
