### ISSUE TITLE
Transient failure in AnnouncerTest testSessionKilled

### ISSUE THREAD

**Issue by fjy** [apache/incubator-druid#2430] opened 2016-02-10 01:41 UTC
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.633 sec <<< FAILURE! - in io.druid.curator.announcement.AnnouncerTest
testSessionKilled(io.druid.curator.announcement.AnnouncerTest)  Time elapsed: 3.17 sec  <<< ERROR!
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /test1
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
    at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155)
    at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:302)
    at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:291)
    at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
    at org.apache.curator.framework.imps.GetDataBuilderImpl.pathInForeground(GetDataBuilderImpl.java:287)
    at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:279)
    at org.apache.curator.framework.imps.GetDataBuilderImpl$1.forPath(GetDataBuilderImpl.java:104)
    at org.apache.curator.framework.imps.GetDataBuilderImpl$1.forPath(GetDataBuilderImpl.java:64)
    at io.druid.curator.announcement.AnnouncerTest.testSessionKilled(AnnouncerTest.java:170)

**Comment by fjy** [comment] 2016-02-20 23:21
Duplicated by #2167

**Comment by gianm** [comment] 2016-03-25 21:10
Reopening this, it's a different stack trace from #2167 so might be a different problem.

**Comment by gianm** [comment] 2016-03-25 21:10
Saw in https://travis-ci.org/druid-io/druid/jobs/118525905 on #2735

**Comment by gianm** [comment] 2018-09-07 05:07
Closing this -- haven't seen it recently and the issue is a couple years old.

**Closed by gianm** 2018-09-07 05:07 UTC
Labels: Area - Testing, Flaky test
