### ISSUE TITLE
Transient test failure - testRunSameAvailabilityGroup(io.druid.indexing.overlord.RemoteTaskRunnerTest)

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#2986] opened 2016-05-18 17:36 UTC
https://travis-ci.org/druid-io/druid/builds/131185400

```
Tests run: 16, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 31.362 sec <<< FAILURE! - in io.druid.indexing.overlord.RemoteTaskRunnerTest
testRunSameAvailabilityGroup(io.druid.indexing.overlord.RemoteTaskRunnerTest)  Time elapsed: 2.208 sec  <<< FAILURE!
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at io.druid.indexing.overlord.RemoteTaskRunnerTest.testRunSameAvailabilityGroup(RemoteTaskRunnerTest.java:202)
```

**Comment by gianm** [comment] 2018-09-07 05:05
Closing this -- haven't seen it recently and the issue is a couple years old.

**Closed by gianm** 2018-09-07 05:05 UTC
Labels: Area - Testing, Flaky test
